name: ev_charging_station
description: EV Charging Station - MQTT monitoring app
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  mqtt_client: ^10.0.0
  google_fonts: ^8.1.0
  fl_chart: ^1.2.0
  firebase_core: ^4.11.0
  firebase_database: ^12.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#0F1923"
  adaptive_icon_foreground: assets/icon/app_icon.png
  web:
    generate: true
    image_path: assets/icon/app_icon.png
    background_color: "#0F1923"
    theme_color: "#00E676"
  macos:
    generate: true
    image_path: assets/icon/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
